### ISSUE TITLE
Prices page in ledger is not loading.

### ISSUE THREAD

**Issue by avinashkanaujiya** [ananthakumaran/paisa#52]
Maybe I did wrong configuration, can anyone guide me?
![image](https://github.com/ananthakumaran/paisa/assets/24972285/ba05356b-09f6-43d2-bbab-b6d6ce914c24)
There is no error in terminal.
The console has below error 

```bash
21.d8eebcce.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'commodity_name')
    at Array.yt (21.d8eebcce.js:1:690)
    at ht (scheduler.b2e36843.js:1:802)
    at z (Toggleable.7c088a46.js:1:553)
    at Ot (index.4c91fe54.js:4:2967)
    at new E (Toggleable.7c088a46.js:1:1170)
    at ot (21.d8eebcce.js:1:4188)
    at Object.p (21.d8eebcce.js:1:5943)
    at ct (scheduler.b2e36843.js:1:8618)
    at rt (scheduler.b2e36843.js:1:8271)
```

**Comment by ananthakumaran** [comment]
Can you open developer tools > Network tab and view the response of `/api/price` call? One of the commodities would have an empty array, the problem is due to that. Still trying to figure out how it could go into that state.

**Comment by avinashkanaujiya** [comment]
In the response, I can see that `AAPL` has the empty array.

**Comment by ananthakumaran** [comment]
Do you have that currency? it's just in your commodity config?

**Comment by avinashkanaujiya** [comment]
Oh, it wasn't in my commodities config, but it is in my portfolio, now I think all the other are resolved.
I think somehow, it should be managed in the code, that if commodities are not added, then it shouldn't try to look for it.

**Comment by ananthakumaran** [comment]
Can you share your transaction with AAPL entry? I will fix the issue, just want to confirm I am fixing the same issue.

**Comment by avinashkanaujiya** [comment]
Here is my apple transaction.
```ledger
2023-05-08 Opening Balance US Stocks
    Assets:Equity:Indmoney                0.69057594 AAPL @ 173.768 USD
    Equity
```

Also just to summarize, as I wasn't clear in my last comment.
I forgot to add `AAPL` stock to my commodities config, after which everything related to prices of commodities stopped working.
Once I added `AAPL` stock to config, everything is working just fine.

**Comment by ananthakumaran** [comment]
is USD your default currency? if not Paisa will still not know how to convert USD to INR. You can instead specify the price in INR (if you don't know the price, just put a dummy value, once you fetch the price from the provider, the doctor page will warn about price mismatch)

I have pushed a fix for the error and the doctor page will also start to warn if it can't convert from commodity to default currency
